kic/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'kic'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('universities/', UniversityView.as_view(), name='university'),
    path(
        'universities/<slug:university_slug>/',
        UniversityDetailView.as_view(),
        name='university_detail',
    ),
    path('training/', TrainingView.as_view(), name='training'),
    path('services/', ServicesView.as_view(), name='services'),
    path('services/<slug:service_slug>/', ServiceDetailView.as_view(), name='service_detail'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', contact_us, name='contact'),
    path('<slug:country_slug>/', CountryDetailView.as_view(), name='country_detail'),
    path(
        'preparations/<slug:preparation_class_slug>/',
        TestPreparationClassDetailView.as_view(),
        name='preparation_class_detail',
    ),
]

kiceducation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kic.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
{% load static %}

<footer
  data-sal="fade"
  data-sal-duration="500"
  data-sal-delay="100"
  data-sal-easing="ease-in-out"
>
  <div class="container-fluid">
    <div class="row g-sm-5 g-3 footer-content">
      <div class="col-12 col-sm-6 col-md-4 col-xl-3 mb-sm-0 mb-1">
        <a href="{% url 'kic:home' %}">
          <img
            src="{% static 'images/logo.png' %}"
            alt=""
            style="width: 150px"
          />
        </a>
        <p class="pt-2">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia
          provident atque beatae aperiam quos, ipsam nobis nisi eligendi
          laudantium reiciendis
        </p>
        <ul class="social-links d-sm-block">
          <li>
            <a href="#" target="_blank" class="social-item"
              ><img
                src="{% static 'images/footer-facebook.svg' %}"
                alt="Facebook icon"
            /></a>
          </li>
          <li>
            <a href="#" class="social-item" target="_blank">
              <img
                src="{% static 'images/footer-messenger.svg' %}"
                alt="Messenger icon"
              />
            </a>
          </li>
          <li>
            <a href="#" target="_blank" class="social-item"
              ><img
                src="{% static 'images/footer-instagram.svg' %}"
                alt="Instagram icon"
            /></a>
          </li>
          <li>
            <a href="#" target="_blank" class="social-item"
              ><img
                src="{% static 'images/footer-linkedin.svg' %}"
                alt="Linkedin icon"
            /></a>
          </li>
          <li>
            <a href="#" target="_blank" class="social-item"
              ><img
                src="{% static 'images/footer-tiktok.svg' %}"
                alt="Tiktok icon"
            /></a>
          </li>
          <li>
            <a href="#" target="_blank" class="social-item"
              ><img
                src="{% static 'images/footer-youtube.svg' %}"
                alt="Youtube icon"
            /></a>
          </li>
        </ul>
      </div>

      <div class="col-12 col-sm-5 col-md-5 col-xl-3 mb-sm-0 mb-2">
        <div class="useful-link-container">
          <ul class="footer-list">
            <h3 class="footer-heading">Quick Links</h3>

            <li>
              <a href="{% url 'kic:about' %}">About KIC</a>
            </li>
            <li>
              <a href="{% url 'kic:services' %}">Services</a>
            </li>

            <li>
              <a href="{% url 'kic:university' %}">Universities</a>
            </li>

            <li>
              <a href="{% url 'kic:training' %}">Training</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-12 col-sm-6 col-md-4 col-xl-3 mb-sm-0 mb-2">
        <div class="useful-link-container">
          <ul class="footer-list">
            <h3 class="footer-heading">Useful Documents</h3>

            <li>
              <a href="#">Experience Letter</a>
            </li>
            <li>
              <a href="#">Recommendation Letter</a>
            </li>

            <li>
              <a href="#">Sample Documents</a>
            </li>
            <li>
              <a href="#">Bio-Data</a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-md-4 col-xl-3 mb-sm-0 mb-2">
        <h3 class="footer-heading">Contact Us</h3>
        <div class="footer-col">
          <ul class="footer-list">
            <li>
              <span class="ri--phone-fill"></span>
              <a href="tel:9705430592">9705430592</a>

              <span>,</span>
              <a href="tel:9705430593">9705430593</a>
              <span>,</span>
              <a href="tel:9705430594">9705430594</a>
            </li>
            <li>
              <span class="ic--round-mail"></span>
              <a href="mailto:{{ KIC_EMAIL_ADDRESS }}">{{ KIC_EMAIL_ADDRESS }}</a>
            </li>
            <li>
              <span class="ic--baseline-location-on"></span>
              <a href="" target="_blank">{{ KIC_ADDRESS }}</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <hr class="footer-line" />
    <div class="copyright">
      <div class="copy-text">
        <span>© 2025 - All Rights reserved. KICEducation</span>
      </div>
      <div class="d-flex gap-2">
        <a href="#" target="_blank">Terms & Conditions</a>
        <span class="text-white">|</span>
        <a href="#" target="_blank">Privacy Policy</a>
      </div>
    </div>
  </div>
</footer>

templates/partials/header.html
{% load static %}

<header id="header">
  <div class="container-fluid">
    <nav class="navbar">
      <section class="navbar__left">
        <a href="{% url 'kic:home' %}" data-no-blank="">
          <img class="logo" src="{% static 'images/logo.png' %}" alt="Logo" />
        </a>
        <div class="burger" id="burger">
          <span class="burger-line"></span>
          <span class="burger-line"></span>
          <span class="burger-line"></span>
        </div>
      </section>

      <section class="navbar__center">
        <span class="overlay"></span>
        <div class="menu" id="menu">
          <div class="menu__header">
            <span class="menu__arrow">
              <i class="bx bx-chevron-left"></i>
            </span>
            <span class="menu__title"></span>
          </div>

          <ul class="menu__inner">
            <li
              class="menu__item menu-close d-flex justify-start align-items-center d-block d-sm-none"
            >
              <a href="#" class="menu__link">
                <svg
                  id="menu_dismiss"
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                >
                  <g
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                  >
                    <path d="M5 12H19">
                      <animate
                        fill="freeze"
                        attributeName="d"
                        dur="0.4s"
                        values="M5 12H19;M12 12H12"
                      ></animate>
                      <set
                        fill="freeze"
                        attributeName="opacity"
                        begin="0.4s"
                        to="0"
                      ></set>
                    </path>
                    <path d="M5 5L19 5M5 19L19 19" opacity="0">
                      <animate
                        fill="freeze"
                        attributeName="d"
                        begin="0.2s"
                        dur="0.4s"
                        values="M5 5L19 5M5 19L19 19;M5 5L19 19M5 19L19 5"
                      ></animate>
                      <set
                        fill="freeze"
                        attributeName="opacity"
                        begin="0.2s"
                        to="1"
                      ></set>
                    </path>
                  </g>
                </svg>
              </a>
            </li>

            <li class="menu__item">
              <a href="{% url 'kic:home' %}" class="menu__link">
                <span>Home</span>
              </a>
            </li>

            <li class="menu__item menu__dropdown">
              <a
                href="javascript:void(0)"
                class="menu__link"
                onclick="event.preventDefault()"
              >
                <span>Study Abroad</span>
                <i class="bx bx-chevron-right"></i>
              </a>
              <div
                class="submenu our-services-dropdown megamenu__text about-dropdown"
              >
                {% for country in countries %}
                <div class="submenu__inner">
                  <ul class="submenu__list">
                    <li>
                      <a href="{{ country.get_absolute_url }}">
                        <img src="{{ country.flag.url }}" alt="{{ country.name }}" />
                        <span>{{ country.name }}</span>
                      </a>
                    </li>
                  </ul>
                </div>
                {% endfor %}
              </div>
            </li>

            <li class="menu__item menu__dropdown">
              <a
                href="javascript:void(0)"
                class="menu__link"
                onclick="event.preventDefault()"
              >
                <span>Test Preparation</span>
                <i class="bx bx-chevron-right"></i>
              </a>

              <div
                class="submenu our-services-dropdown megamenu__text about-dropdown"
              >
                {% for preparation_class in preparation_classes %}
                <div class="submenu__inner">
                  <ul class="submenu__list">
                    <li>
                      <a href="{{ preparation_class.get_absolute_url }}">
                        <img src="{{ preparation_class.logo.url }}" alt="{{ preparation_class.name }}" />
                        <span>{{ preparation_class.name }}</span>
                      </a>
                    </li>
                  </ul>
                </div>
                {% endfor %}
              </div>
            </li>

            <li class="menu__item">
              <a href="{% url 'kic:university' %}" class="menu__link">
                <span>University</span>
              </a>
            </li>
            <li class="menu__item">
              <a href="{% url 'kic:training' %}" class="menu__link">
                <span>Training</span>
              </a>
            </li>
            <li class="menu__item menu__dropdown">
              <a href="{% url 'kic:services' %}" class="menu__link">
                <span>Services</span>
              </a>
            </li>

            <li class="menu__item">
              <a href="{% url 'kic:about' %}" class="menu__link">
                <span>About Us</span>
              </a>
            </li>

            <li class="menu__item">
              <a href="{% url 'kic:contact' %}" class="menu__link">
                <span>Contact Us</span>
              </a>
            </li>

            <li class="menu__item">
              <a href="" class="btn-custom"><span>Eligibility Check</span></a>
            </li>
          </ul>
        </div>
      </section>
    </nav>
  </div>
</header>