kic/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'kic'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('universities/', UniversityView.as_view(), name='university'),
    path(
        'universities/<slug:university_slug>/',
        UniversityDetailView.as_view(),
        name='university_detail',
    ),
    path('training/', TrainingView.as_view(), name='training'),
    path('services/', ServicesView.as_view(), name='services'),
    path('services/<slug:service_slug>/', ServiceDetailView.as_view(), name='service_detail'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', contact_us, name='contact'),
    path('<slug:country_slug>/', CountryDetailView.as_view(), name='country_detail'),
    path(
        'preparations/<slug:preparation_class_slug>/',
        TestPreparationClassDetailView.as_view(),
        name='preparation_class_detail',
    ),
]

kiceducation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kic.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kic/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.functions import Lower
from django.urls import reverse
from django.utils.text import slugify


class Country(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    flag = models.ImageField(upload_to='countries/')
    study_reason_overview = models.TextField(help_text='Overview for reason to study in a country.')
    image_1 = models.ImageField(
        upload_to='countries/',
        blank=True,
        null=True,
        help_text='Optional image for why study section.',
    )
    image_2 = models.ImageField(
        upload_to='countries/',
        blank=True,
        null=True,
        help_text='Optional image for reasons to study section.',
    )

    class Meta:
        verbose_name_plural = 'countries'
        constraints = [
            models.UniqueConstraint(
                Lower('name'),
                name='unique_lower_name_country',
                violation_error_message='Country with that name already exists.',
            ),
        ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('kic:country_detail', kwargs={'country_slug': self.slug})


class WhyStudy(models.Model):
    """Model representing why student might choose to study in a country."""

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='why_study')
    point = models.CharField(max_length=255)
    order = models.PositiveSmallIntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=['country', 'point'], name='unique_country_point'),
    #     ]

    def __str__(self):
        return f'{self.country.name} - {self.point}'


class CountryFact(models.Model):
    """Model representing facts of a country."""

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='facts')
    fact = models.CharField(max_length=255)
    order = models.PositiveSmallIntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    # class Meta:
    #     constraints = [
    #         models.UniqueConstraint(fields=['country', 'fact'], name='unique_country_fact', violation_error_message='Country with this fact already exists.'),
    #     ]

    def __str__(self):
        return f'Facts about {self.country.name}'


class StudyReason(models.Model):
    """Model representing study reasons of a country."""

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='reasons')
    reason_title = models.CharField(max_length=255)
    reason_description = models.TextField(max_length=500)
    position = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f'{self.country.name} - {self.reason_title}'


class Requirement(models.Model):
    """Model representing requirements to study in a country."""

    class LevelChoices(models.TextChoices):
        DIPLOMA = 'DIPLOMA', 'Diploma'
        BACHELOR = 'BACHELOR', 'Bachelor'
        MASTER = 'MASTER', 'Master'
        PHD = 'PhD', 'PhD'

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='requirements')
    level = models.CharField(max_length=20, choices=LevelChoices.choices)
    academic = models.TextField(
        max_length=500, help_text='Academic requirements such as minimum GPA, prior degree, etc.'
    )
    language = models.TextField(
        max_length=500, help_text='Language test requirements (IELTS, PTE, TOEFL, etc.).'
    )

    def __str__(self):
        return f'Study requirement for {self.country.name}'


class CostAndBudget(models.Model):
    """Model representing estimated costs and budget to study in a country."""

    class BudgetItemChoice(models.TextChoices):
        TUITION = 'TUITION', 'Tuition (per year)'
        VISA = 'VISA', 'Visa application fee'

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='budgets')
    item = models.CharField(max_length=30, choices=BudgetItemChoice.choices)
    estimated_amount = models.CharField(max_length=100)

    def __str__(self):
        return f'Estimated cost & budget for {self.country.name}'


class StepProcess(models.Model):
    """Model representing step by step process to study in a country."""

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='processes')
    title = models.CharField(max_length=150)
    description = models.TextField(max_length=500)
    order = models.PositiveSmallIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'processes'
        ordering = ['order', '-created_at']

    def __str__(self):
        return f'Step by step process for {self.country.name}'


class FAQ(models.Model):
    """Model representing frequently asked questions of a country."""

    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='faqs')
    question = models.CharField(max_length=150)
    answer = models.CharField(max_length=255)
    position = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['position', '-created_at']

    def __str__(self):
        return f'{self.country.name} - {self.question}'


class University(models.Model):
    class StatusChoices(models.TextChoices):
        ACTIVE = 'active', 'Active Partner'
        INACTIVE = 'inactive', 'No Current Partnership'
        POTENTIAL = 'potential', 'Potential Partner'

    name = models.CharField(max_length=255, help_text='Official name of the university.')
    slug = models.SlugField(max_length=255, unique=True)
    logo = models.ImageField(upload_to='university_logos/')
    description = models.TextField(help_text='Description of the university.')
    website = models.URLField()
    established_date = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=150, blank=True, null=False, default='')
    enrollment_season = models.CharField(max_length=150, help_text='e.g. January and September')
    ranking = models.PositiveIntegerField(
        blank=True, null=True, help_text='World or national ranking if available.'
    )
    country = models.ForeignKey(Country, on_delete=models.PROTECT, related_name='universities')
    status = models.CharField(
        max_length=20, choices=StatusChoices.choices, default=StatusChoices.ACTIVE, db_index=True
    )
    is_featured = models.BooleanField(default=False, db_index=True)

    class Meta:
        verbose_name_plural = 'universities'

    def __str__(self):
        return f'{self.name} ({self.country.name})'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('kic:university_detail', kwargs={'university_slug': self.slug})


class TestPreparationClass(models.Model):
    """Model representing test preparation classes provided by consultancy."""

    name = models.CharField(max_length=100, unique=True, help_text='e.g. IELTS, PTE')
    slug = models.CharField(max_length=100, unique=True)
    logo = models.ImageField(upload_to='preparation_classes/')
    overview = models.TextField(help_text='Overview of this test preparation class.')

    def __str__(self):
        return f'{self.name} Preparation Classes'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('kic:preparation_class_detail', kwargs={'preparation_class_slug': self.slug})


class Service(models.Model):
    """Model representing services provided by consultancy."""

    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    icon_name = models.CharField(max_length=20, help_text='e.g., user, home, settings')
    overview = models.TextField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('kic:service_detail', kwargs={'service_slug': self.slug})


class Mission(models.Model):
    """Model representing consultancy missions."""

    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    icon_name = models.CharField(max_length=20, help_text='e.g., user, home, settings')

    def __str__(self):
        return self.title


class Achievement(models.Model):
    """Model representing consultancy achievements."""

    title = models.CharField(max_length=255)
    date = models.DateField(blank=True, null=True)
    image = models.ImageField(upload_to='achievements/')

    def __str__(self):
        return self.title


class Counsellor(models.Model):
    # REVIEW: counsellor might not be user of the system?
    # user = models.OneToOneField(
    #     settings.AUTH_USER_MODEL,
    #     on_delete=models.CASCADE,
    #     help_text='System user account linked to this counsellor.',
    # )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15, unique=True)
    position = models.CharField(max_length=100, help_text='Position in the consultancy')

kic/forms.py
from django import forms


class ContactusForm(forms.Form):
    full_name = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Full name'})
    )
    email = forms.EmailField(
        max_length=255, widget=forms.EmailInput(attrs={'placeholder': 'Email address'})
    )
    phone_number = forms.CharField(
        max_length=10, widget=forms.TextInput(attrs={'placeholder': 'Phone number'})
    )
    subject = forms.CharField(
        max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Subject'})
    )
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(attrs={'placeholder': 'Enter your message', 'rows': 3}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

kic/views.py
import logging
from typing import Any

from django.conf import settings
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView

from .forms import ContactusForm
from .models import (
    Achievement,
    Country,
    Counsellor,
    Event,
    Mission,
    Service,
    Testimonial,
    TestPreparationClass,
    University,
)

logger = logging.getLogger(__name__)


class HomeView(TemplateView):
    template_name = 'kic/index.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['recent_events'] = Event.objects.filter(status=Event.StatusChoices.PUBLISHED)[:3]
        context['services'] = Service.objects.all()
        context['counsellors'] = Counsellor.objects.filter(is_active=True)
        context['institutions'] = University.objects.filter(
            status=University.StatusChoices.ACTIVE, is_featured=True
        )
        context['testimonials'] = Testimonial.objects.filter(is_featured=True)
        return context


class UniversityView(TemplateView):
    template_name = 'kic/university.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['universities'] = University.objects.filter(status=University.StatusChoices.ACTIVE)
        return context


class UniversityDetailView(DetailView):
    template_name = 'kic/university_detail.html'
    context_object_name = 'university'
    slug_url_kwarg = 'university_slug'

    def get_queryset(self):
        return University.objects.filter(status=University.StatusChoices.ACTIVE)


class TrainingView(TemplateView):
    template_name = 'kic/training.html'


class ServicesView(TemplateView):
    template_name = 'kic/services.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        return context


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'kic/service_detail.html'
    context_object_name = 'service'
    slug_url_kwarg = 'service_slug'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        service = self.object
        related_services = Service.objects.exclude(slug=service.slug)
        context['related_services'] = related_services
        return context


class AboutView(TemplateView):
    template_name = 'kic/about.html'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['achievements'] = Achievement.objects.all()[:5]
        context['missions'] = Mission.objects.all()[:3]
        return context


def contact_us(request):
    if request.method == 'POST':
        form = ContactusForm(request.POST)
        if form.is_valid():
            user_email: str = form.cleaned_data.get('email')
            subject: str = form.cleaned_data.get('subject')
            message = form.cleaned_data.get('message')

            email = EmailMessage(
                subject=subject,
                body=message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[settings.DEFAULT_TO_EMAIL],
                reply_to=[user_email],
            )
            email.send()
            return redirect('kic:contact')
    else:
        form = ContactusForm()
    return render(request, 'kic/contact.html', {'form': form})


class CountryDetailView(DetailView):
    model = Country
    template_name = 'kic/country_detail.html'
    context_object_name = 'country'
    slug_url_kwarg = 'country_slug'

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        country = self.object
        context['why_study'] = country.why_study.all()
        context['facts'] = country.facts.all()
        context['reasons'] = country.reasons.all()
        context['requirements'] = country.requirements.all()
        context['budgets'] = country.budgets.all()
        context['step_processes'] = country.processes.all()[:4]
        context['faqs'] = country.faqs.all()
        return context


class TestPreparationClassDetailView(DetailView):
    model = TestPreparationClass
    template_name = 'kic/test_preparation_class_detail.html'
    context_object_name = 'preparation_class'
    slug_url_kwarg = 'preparation_class_slug'


class EventDetailView(DetailView):
    model = Event
    template_name = 'kic/event_detail.html'
    context_object_name = 'event'
    slug_url_kwarg = 'event_slug'

    def get_queryset(self):
        return Event.objects.filter(status=Event.StatusChoices.PUBLISHED)

kic/templates/kic/country_detail.html
{% extends "base.html" %}

{% block title %}
{{ country.name }} - {{ SITE_NAME }}
{% endblock title %}

{% block content %}
<section class="py-5 university-details text-white d-flex align-items-center justify-content-center position-relative">
  <!-- Overlay -->
  <div class="play-overlay"></div>

  <!-- Text Content -->
  <div class="content text-center" style="position: relative; z-index: 2" data-sal="fade" data-sal-duration="800" data-sal-delay="200" data-sal-easing="ease-in-out">
    <h2 data-sal="slide-up" data-sal-duration="600" data-sal-delay="300">
      Study in
    </h2>
    <p data-sal="slide-up" data-sal-duration="600" data-sal-delay="500">
      {{ country.name }} From Nepal
    </p>
  </div>
</section>

<!-- why study section  -->
<section class="py-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8" data-sal="slide-right" data-sal-duration="800" data-sal-delay="200">
        <h2>
          Why Study in
          <span style="color: var(--color-primary)">{{ country.name }} From Nepal?</span>
        </h2>
        <ul class="university-details-list px-3">
          {% for study in why_study %}
          <li>{{ study.point }}</li>
          {% empty %}
          <p>No why study points available.</p>
          {% endfor %}
        </ul>
      </div>
      {% if country.image_1 %}
      <div class="col-md-4" data-sal="slide-left" data-sal-duration="800" data-sal-delay="200">
        <img
          class="img-fluid rounded-3 overflow-hidden"
          style="height: auto"
          src="{{ country.image_1.url }}"
          alt="why study in {{ country.name }} image"
        />
      </div>
      {% endif %}
      <div class="col-md-12 text-center pt-3">
        <div class="">
          <a href="{% url 'kic:contact' %}" class="btn btn-outline-primary">
            Want to Study in {{ country.name }}? Sign Up for a Free consultation session
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- why study section end  -->

<!-- fact section  -->
<section class="py-5" style="background-color: #f4f6f7c3" data-sal="fade" data-sal-duration="600" data-sal-delay="100" data-sal-easing="ease">
  <div class="container-fluid">
    <div class="row">
      <h2>
        Facts about
        <span style="color: var(--color-primary)">{{ country.name }}</span>
      </h2>
      {% comment %} loop start here {% endcomment %}
      <div class="col-md-6" data-sal="slide-up" data-sal-duration="500" data-sal-delay="100" data-sal-easing="ease-in-out">
        <ul class="university-details-list px-3">
          {% for fact in facts %}
          <li>{{ fact.fact }}</li>
          {% empty %}
          <p>No facts about country available.</p>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- fact section end -->

<!-- reason section  -->
<section class="py-5" data-sal="fade" data-sal-duration="600" data-sal-delay="100" data-sal-easing="ease">
  <div class="container-fluid">
    <div class="row">
      {% if country.image_2 %}
      <div class="col-md-4 py-2" data-sal="slide-right" data-sal-duration="800" data-sal-delay="200">
        <img
          class="img-fluid rounded-3 overflow-hidden"
          style="height: auto"
          src="{{ country.image_2.url }}"
          alt="Reason to study in {{ country.name }} image"
        />
      </div>
      {% endif %}

      <div class="col-md-8" data-sal="slide-left" data-sal-duration="800" data-sal-delay="200">
        <h2>
          Reasons to
          <span style="color: var(--color-primary)">Study in {{ country.name }}</span>
        </h2>
      <p>{{ country.study_reason_overview }}</p>
        <div class="row">
          {% for reason in reasons %}
          <div class="col-md-6 px-4">
            <h4 class="mb-1">{{ forloop.counter }}. {{ reason.reason_title }}</h4>
            <p style="text-align: justify; font-size: 14px">{{ reason.reason_description }}</p>
          </div>
          {% empty %}
          <p>No reasons to study available.</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Requirement cost  -->
<section class="py-5" style="background-color: #f4f6f7c3" data-sal="fade" data-sal-duration="600" data-sal-delay="100" data-sal-easing="ease">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12" data-sal="slide-left" data-sal-duration="500" data-sal-delay="100" data-sal-easing="ease-in-out">
        <h2>
          Requirements
          <span style="color: var(--color-primary)">to Study in {{ country.name }}</span>
        </h2>

        <div class="table-wrap">
          <table class="styled-table">
            <thead>
              <tr>
                <th>Level</th>
                <th>Academic (typical)</th>
                <th>IELTS / PTE (typical)</th>
              </tr>
            </thead>
            <tbody>
              {% for requirement in requirements %}
              <tr>
                <td>{{ requirement.get_level_display }}</td>
                <td>{{ requirement.academic }}</td>
                <td>{{ requirement.language }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="3" class="text-center">No requirements available.</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <p class="pt-2" style="font-size: 14px">
          * Requirements may differ depending on the university and course.
          Please refer to the official university website for details. You can
          also visit our IELTS and PTE pages for tips on English test
          preparation.
        </p>
      </div>

      <div class="col-md-12 py-3" data-sal="slide-right" data-sal-duration="500" data-sal-delay="100" data-sal-easing="ease-in-out">
        <h2>
          Costs &
          <span style="color: var(--color-primary)">Budget (Typical)</span>
        </h2>

        <div class="table-wrap">
          <table class="styled-table">
            <thead>
              <tr>
                <th>Item</th>
                <th>Estimated Amount</th>
              </tr>
            </thead>
            <tbody>
              {% for budget in budgets %}
              <tr>
                <td>{{ budget.get_item_display }}</td>
                <td>{{ budget.estimated_amount }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="2" class="text-center">No costs & budget available.</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- process  -->
<section class="py-5">
  <div class="container-fluid">
    <div class="row text-center justify-content-center mb-2">
      <div class="col-xl-7 col-lg-10">
        <h2 class="mb-1">
          Study in {{ country.name }}:
          <span style="color: var(--color-primary)">Step by step process</span>
        </h2>
        <p class="text-muted text-center">
          We’re very proud of the path we’ve taken. Explore the history that
          made us the company we are today and let us guide you through each
          step of your study abroad journey.
        </p>
      </div>
    </div>

    <div class="row process-step">
      {% for step_process in step_processes %}
      <div class="col-md-3 text-center process-item" data-sal="fade" data-sal-duration="600" data-sal-delay="100">
        <div class="circle">
          <p>{{ forloop.counter }}</p>
        </div>
        <h3>{{ step_process.title }}</h3>
        <p>{{ step_process.description }}</p>
      </div>
      {% empty %}
      <p class="text-center">No step by step process available.</p>
      {% endfor %}

      <div class="col-md-12 text-center pt-3">
        <div class="">
          <a href="contact.html" class="btn btn-outline-primary">
            Want to Study in {{ country.name }}? Sign Up for a Free consultation session
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- faq's  -->
<section class="pt-2 pb-5" data-sal="fade" data-sal-duration="600" data-sal-delay="100" data-sal-easing="ease">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="card card-style1 border-0 shadow-lg">
          <div class="card-body p-2 p-md-5 p-xl-5">
            <div class="text-center">
              <h2 class="">
                Frequently
                <span style="color: var(--color-primary)">Asked Questions</span>
              </h2>
            </div>
            <div id="accordion" class="accordion-style">
              {% for faq in faqs %}
              <div class="card mb-3 faq-item" data-sal="slide-up" data-sal-duration="500" data-sal-delay="100">
                <div class="card-header" id="heading-{{ faq.id }}">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse-{{ faq.id }}" aria-expanded="true" aria-controls="collapse-{{ faq.id }}">
                      <span class="text-theme-secondary me-2">Q.</span>{{ faq.question }}
                    </button>
                  </h5>
                </div>
                <div id="collapse-{{ faq.id }}" class="collapse" aria-labelledby="heading-{{ faq.id }}" data-bs-parent="#accordion">
                  <div class="card-body">
                    {{ faq.answer }}
                  </div>
                </div>
              </div>
              {% empty %}
              <p class="text-center">No frequently asked questions available.</p>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

kic/templates/kic/event_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{ event.title }} - {{ SITE_NAME }}
{% endblock title %}

{% block content %}
<section class="py-5 university-details text-white d-flex align-items-center justify-content-center position-relative">
  <!-- Overlay -->
  <div class="play-overlay"></div>

  <!-- Text Content -->
  <div class="content text-center" style="position: relative; z-index: 2" data-sal="fade" data-sal-duration="800" data-sal-delay="200" data-sal-easing="ease-in-out">
    <h2 data-sal="slide-up" data-sal-duration="600" data-sal-delay="300">
      {{ event.title }}
    </h2>
  </div>
</section>

<section class="py-5">
  <div class="container-fluid">
    <div class="row">
      <h3>Working on this page ........</h3>
    </div>
  </div>
</section>
{% include "kic/partial/newsletter.html" %}
{% endblock content %}

kic/templates/kic/services.html
{% extends "base.html" %}

{% block title %}
Services - {{ SITE_NAME }}
{% endblock title %}

{% block content %}
<section class="py-5 about-us text-white d-flex align-items-center justify-content-center position-relative">
  <!-- Overlay -->
  <div class="play-overlay"></div>

  <!-- Text Content -->
  <div class="content text-center" style="position: relative; z-index: 2" data-sal="fade" data-sal-duration="800" data-sal-delay="200" data-sal-easing="ease-in-out">
    <h2 data-sal="slide-up" data-sal-duration="600" data-sal-delay="300">
      Service We Provide
    </h2>
    <p data-sal="slide-up" data-sal-duration="600" data-sal-delay="500">
      KIC guides you through every step — from university selection to
      pre-departure — making your study abroad journey smooth and stress-free.
    </p>
  </div>
</section>

<!-- services section start -->
<div class="services py-3" data-sal="fade" data-sal-duration="600" data-sal-delay="100" data-sal-easing="ease">
  <div class="container-fluid">
    <div class="row g-4 my-3">
      {% for service in services %}
      <div class="col-lg-3" data-sal="slide-up" data-sal-duration="500" data-sal-delay="100" data-sal-easing="ease-in-out">
        <div class="service-item h-100 d-flex flex-column">
          <!-- service icon here -->
          <h4 class="py-2 mb-0 mt-2">{{ service.name }}</h4>
          <p class="flex-grow-1">{{ service.overview|truncatewords:10 }}</p>
          <div class="text-button mt-1">
            <a href="{{ service.get_absolute_url }}">Read More <i class="fa fa-arrow-right"></i></a>
          </div>
        </div>
      </div>
      {% empty %}
      <p class="text-center">No services available.</p>
      {% endfor %}
    </div>
  </div>
</div>
<!-- services section end -->
{% include "kic/partial/newsletter.html" %}
{% endblock content %}